apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: inventory-failover
  name: inventory-failover
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-failover
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: inventory-failover
    spec:
      containers:
      - image: springframeworkguru/kbe-inventory-failover
        name: kbe-inventory-failover
        resources: {}
status: {}
